# Generated by Django 4.2.6 on 2024-01-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mar24YatraReg',
            new_name='mar24yatra_reg',
        ),
    ]
