# Generated by Django 4.2.6 on 2024-01-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0002_rename_mar24yatrareg_mar24yatra_reg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mar24yatra_reg',
            table='mar24yatra_reg',
        ),
    ]
