# Generated by Django 4.2.6 on 2024-01-22 10:38

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0003_alter_mar24yatra_reg_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mar24yatra_reg',
            name='confirm_time',
            field=models.DateTimeField(default=timezone.now),

            # Import timezone from django.utils if not already imported
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mar24yatra_reg',
            name='rec_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
    ]
