# Generated by Django 4.2.6 on 2024-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0006_alter_mar24yatra_reg_confirm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mar24yatra_reg',
            name='confirm_time',
            field=models.DateTimeField(),
        ),
    ]
