# Generated by Django 4.2.6 on 2024-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0007_alter_mar24yatra_reg_confirm_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mar24yatra_reg',
            name='confirm_time',
        ),
    ]
