# Generated by Django 4.2.6 on 2024-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0009_remove_mar24yatra_reg_rec_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mar24yatra_reg',
            name='rec_time',
        ),
    ]
