# Generated by Django 4.2.6 on 2024-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra2024', '0010_remove_mar24yatra_reg_rec_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraUser',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('client_id', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('SrNo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'YatraUser',
            },
        ),
    ]
